services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:admin@localhost:27017/?authSource=admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:   