services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - ./backend/.env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/?authSource=admin" --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data: